version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest
    restart: always
    ports:
      - "8080:8080"
    env_file:   
      - .env
    depends_on:
      - db-initializer

  db-initializer:
    build:
      context: ./db-initializer 
    depends_on:
      - mssql-db
    environment:
      DB_HOST: mssql-db
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: Ahmed1234!
      DB_DATABASE: master
    command: bash -c 'sleep 30s && /opt/mssql-tools/bin/sqlcmd -S mssql-db -U sa -P Ahmed1234! -d master -i docker-entrypoint-initdb.d/init.sql;'
    
  mssql-db:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-db
    restart: always
    environment:
      SA_PASSWORD: Ahmed1234!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # command: >
    #   bash -c '
    #   sleep 30s && /opt/mssql-tools/bin/sqlcmd -S host.docker.internal -U sa -P Ahmed1234! -d master -i docker-entrypoint-initdb.d/init.sql;
    #   echo "All done!";
    #   '



volumes:
  mssql-data:

      